In [1]:
import numpy as np
#あやめのデータを準備
from sklearn.datasets import load_iris
data = load_iris()
X = data.data

In [2]:
dir(data)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
X.shape
#データ個数　特微量

(150, 4)

In [4]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [5]:
data.feature_names
#特徴の意味

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
y = data.target #.targetにラベルが入っている

In [7]:
y.shape

(150,)

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
from sklearn import linear_model
clf = linear_model.LogisticRegression()

In [14]:
n_samples = X.shape[0]
n_train = n_samples // 2
n_test = n_samples - n_train


In [15]:
train_index = range(0,n_train)
test_index = range(n_train,n_samples)

In [16]:
np.array(train_index),np.array(test_index)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74]),
 array([ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149]))

In [17]:
X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [19]:
clf.fit(X_train, y_train)
print(clf.score(X_train,y_train))

1.0


In [21]:
print(clf.score(X_test,y_test))

0.3333333333333333


In [22]:
clf.predict(X_test),y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2]))

In [23]:
wrong = 0
for i,j in zip(clf.predict(X_test), y_test):
    if i==j:
        print(i,j)
    else:
        print(i,j," Wrong!")
        wrong+=1

1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!
1 2  Wrong!


In [24]:
print ("{0}/{1}={2}".format(wrong,n_test,1-wrong/n_test))

50/75=0.33333333333333337


In [25]:
from sklearn.model_selection import ShuffleSplit
ss = ShuffleSplit(n_splits=1,
                  train_size=0.5,
                  test_size=0.5,
                  random_state=0)



In [26]:
train_index,test_index= next(ss.split(X))

In [27]:
list(train_index),list(test_index)

([3,
  149,
  98,
  6,
  68,
  109,
  96,
  12,
  102,
  120,
  104,
  128,
  46,
  11,
  110,
  124,
  41,
  148,
  1,
  113,
  139,
  42,
  4,
  129,
  17,
  38,
  5,
  53,
  143,
  105,
  0,
  34,
  28,
  55,
  75,
  35,
  23,
  74,
  31,
  118,
  57,
  131,
  65,
  32,
  138,
  14,
  122,
  19,
  29,
  130,
  49,
  136,
  99,
  82,
  79,
  115,
  145,
  72,
  77,
  25,
  81,
  140,
  142,
  39,
  58,
  88,
  70,
  87,
  36,
  21,
  9,
  103,
  67,
  117,
  47],
 [114,
  62,
  33,
  107,
  7,
  100,
  40,
  86,
  76,
  71,
  134,
  51,
  73,
  54,
  63,
  37,
  78,
  90,
  45,
  16,
  121,
  66,
  24,
  8,
  126,
  22,
  44,
  97,
  93,
  26,
  137,
  84,
  27,
  127,
  132,
  59,
  18,
  83,
  61,
  92,
  112,
  2,
  141,
  43,
  10,
  60,
  116,
  144,
  119,
  108,
  69,
  135,
  56,
  80,
  123,
  133,
  106,
  146,
  50,
  147,
  85,
  30,
  101,
  94,
  64,
  89,
  91,
  125,
  48,
  13,
  111,
  95,
  20,
  15,
  52])

In [28]:
X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]



In [29]:
y_train, y_test

(array([0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2, 0,
        0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0,
        2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1, 1,
        1, 1, 0, 0, 0, 2, 1, 2, 0]),
 array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
        0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
        0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1,
        1, 2, 0, 0, 2, 1, 0, 0, 1]))

In [30]:
clf.fit(X_train, y_train)

LogisticRegression()

In [31]:
print(clf.score(X_train,y_train))

0.9733333333333334


In [32]:
print(clf.score(X_test,y_test))

0.9333333333333333


In [33]:
wrong = 0
for i,j in zip(clf.predict(X_test), y_test):
    if i==j:
        print(i,j)
    else:
        print(i,j," Wrong!")
        wrong+=1



2 2
1 1
0 0
2 2
0 0
2 2
0 0
1 1
1 1
1 1
2 2
1 1
1 1
1 1
1 1
0 0
1 1
1 1
0 0
0 0
2 2
1 1
0 0
0 0
1 2  Wrong!
0 0
0 0
1 1
1 1
0 0
2 2
1 1
0 0
2 2
2 2
1 1
0 0
2 1  Wrong!
1 1
1 1
2 2
0 0
2 2
0 0
0 0
1 1
2 2
2 2
1 2  Wrong!
2 2
1 1
2 2
1 1
1 1
2 2
1 2  Wrong!
1 2  Wrong!
2 2
1 1
2 2
1 1
0 0
2 2
1 1
1 1
1 1
1 1
2 2
0 0
0 0
2 2
1 1
0 0
0 0
1 1


In [34]:
print ("{0}/{1}={2}".format(wrong,n_test,1-wrong/n_test))

5/75=0.9333333333333333
